# Generated by Django 6.0.6 on 2026-08-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('recurso_natural', 'Recurso natural'), ('infraestructura', 'Infraestructura')], max_length=20)),
                ('subtipo', models.CharField(blank=True, help_text='Ejemplo: Río, Puente, Vía, Hospital, Montaña', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('icono', models.CharField(blank=True, help_text='Identificador del icono a usar en el mapa (opcional)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Punto de interés',
                'verbose_name_plural': 'Puntos de interés',
            },
        ),
    ]
