# Generated by Django 6.0.6 on 2026-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='costo_entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo en dólares', max_digits=6),
        ),
        migrations.AddField(
            model_name='lugar',
            name='horario',
            field=models.CharField(blank=True, help_text='Ejemplo: 08:00 - 18:00', max_length=100, null=True),
        ),
    ]
