# Generated by Django 6.0.6 on 2026-08-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_lugar_costo_entrada_lugar_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aprobado',
            field=models.BooleanField(default=True, help_text='Los eventos sugeridos por el público quedan sin aprobar hasta que el admin los revisa.'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='aprobado',
            field=models.BooleanField(default=True, help_text='Los lugares sugeridos por el público quedan sin aprobar hasta que el admin los revisa; no aparecen en el mapa público hasta entonces.'),
        ),
    ]
