# Generated by Django 6.0.6 on 2026-08-24 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0004_evento_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video')], max_length=10)),
                ('archivo', models.FileField(blank=True, help_text='Foto, o un archivo de video si no vas a usar un link de YouTube.', null=True, upload_to='lugares/multimedia/')),
                ('url_video', models.URLField(blank=True, help_text='Link de YouTube (opcional si subes un archivo de video).')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('aprobado', models.BooleanField(default=True, help_text='Las fotos/videos sugeridos por el público quedan sin aprobar hasta que el admin los revisa.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='lugares.lugar')),
            ],
            options={
                'verbose_name': 'Foto o video',
                'verbose_name_plural': 'Fotos y videos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
