# Generated by Django 6.0.6 on 2026-08-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0005_multimedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='parroquia',
            field=models.CharField(blank=True, help_text='Ejemplo: La Maná, Guasaganda, Pucayacu, El Carmen, El Triunfo', max_length=100),
        ),
    ]
