# Generated by Django 6.0.6 on 2026-08-26 21:19

import django.core.validators
import lugares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0006_lugar_parroquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='archivo',
            field=models.FileField(blank=True, help_text='Foto (jpg, png, gif, webp) o video (mp4, webm, mov), máx. 25 MB. O usa un link de YouTube.', null=True, upload_to='lugares/multimedia/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov']), lugares.models.validar_tamano_multimedia]),
        ),
    ]
