# Generated by Django 6.0.6 on 2026-08-24 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0002_lugar_costo_entrada_lugar_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('punto_partida', models.CharField(help_text='Ejemplo: Parque Central de La Maná', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_transporte', models.CharField(choices=[('vehiculo', 'Vehículo'), ('a_pie', 'A pie'), ('bicicleta', 'Bicicleta'), ('bus', 'Bus')], default='vehiculo', max_length=20)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('tiempo_estimado', models.CharField(blank=True, help_text='Ejemplo: 45 min', max_length=50)),
                ('trazado', models.JSONField(help_text='Lista de puntos [[lat, lng], ...] que forman la ruta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='lugares.lugar')),
            ],
        ),
    ]
